// Auth Types
export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const SIGN_UP = "SIGN_UP"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"
export const FORGET_PASS = "FORGET_PASS"
export const FORGET_PASS_SUCCESS = "FORGET_PASS_SUCCESS"
export const FORGET_PASS_FAILURE = "FORGET_PASS_FAILURE"

// Tabs Types
export const LOAD_NOTIFICATIONS = "LOAD_NOTIFICATIONS"
export const LOAD_NOTIFICATIONS_SUCCESS = "LOAD_NOTIFICATIONS_SUCCESS"
export const LOAD_NOTIFICATIONS_FAILURE = "LOAD_NOTIFICATIONS_FAILURE"
export const LOAD_ACCOUNT = "LOAD_ACCOUNT"
export const LOAD_HOME = "LOAD_HOME"